Qc report
BCCDC-PHL/dehost-and-verify-illumina pull request #9
Opened 2020-09-23 19:50 UTC by DiDigsDNA

Wanted to read in the analysis stage from the nextflow pipeline but couldn't figure out how to access it. 
This parses for bracken output filenames for 'pre_dehosting' or 'post_dehosting' in and appends respective strings to qc report fieldnames.

Pending: combining pre- and post-dehosting summaries side by side.

2020-09-24 22:39 UTC, dfornika commented
Could you modify this:

https://github.com/BCCDC-PHL/dehost-and-verify-illumina/blob/efcc5f6438f18c1820ca83fc0d22fc5adac48e65/modules/parse_bracken_output.nf#L13-L16

...to include the `--analysis_stage` flag that you've added to `parse_bracken_output.py`?
like this:
```
parse_bracken_output.py \ 
       --host_name "${host_name}" \ 
       --pathogen_name "${pathogen_name}" \
        --analysis_stage ${analysis_stage} \
       ${bracken_output} > ${sample_id}_pathogen_host_read_summary_${analysis_stage}.tsv 
```

2020-09-24 22:42 UTC, dfornika commented on bin/parse_bracken_output.py
> +def get_analysis_stage(path_to_bracken_output):
I'd prefer to get this info from the `--analysis_stage` command-line flag.

2020-09-24 22:43 UTC, dfornika requested changes
I've made a suggestion in the main 'Conversation' for this PR on how to incorporate the new `--analysis_stage` flag into the workflow.

Let's do that, then use the value from the command-line flag.

2020-09-24 23:10 UTC, dfornika commented
Supports #7

2020-09-29 22:46 UTC, dfornika approved these changes

2020-09-29 22:52 UTC, dfornika commented
This is looking good @DiDigsDNA. If you'd like, we could merge this into master and you could continue the next steps in another pull-request. Or if you're already pushing ahead on this branch then you can continue pushing here. Feel free to request another review (or ping me on slack) when you'd like me to take another look.

2020-11-05 22:07 UTC, dfornika commented
This is looking great @DiDigsDNA. The last step will be to collect all of the merged dehosting reports together into a single file. The Nextflow `collectFile` operator can be used for this:

https://www.nextflow.io/docs/latest/operator.html#collectfile

It has an option called `keepheader` that can be used to combine multiple files that share a common header.

2020-11-16 22:46 UTC, DiDigsDNA commented
@dfornika 
There are now 4 datasets (the original plus 3 the following modified sets):
     fake1_R1.fastq.gz, fake1_R2.fastq.gz (top 10 reads of each removed)
     fake2_R1.fastq.gz, fake2_R2.fastq.gz (top 20 reads of each removed)
     fake3_R1.fastq.gz, fake3_R2.fastq.gz (bottom  30 reads of each removed)
The ran in the pipeline on sabin without error and all produced a <sampleID>_dehosting_report.tsv with the correct output format.

2020-11-18 18:50 UTC, dfornika approved these changes

2020-11-18 18:50 UTC, merged